allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': set this to true or false
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
