allowBuilds:
  "@prisma/engines": true
  "@sentry/cli": true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  "@radix-ui/react-slot": "1.2.5"
  "@radix-ui/react-primitive": "2.1.5"
