import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
  admin: [
    PERMISSIONS.DASHBOARD.ACCESS,
    PERMISSIONS.CUISINES.VIEW,
    PERMISSIONS.CUISINES.CREATE,
    PERMISSIONS.CUISINES.UPDATE,
    PERMISSIONS.CUISINES.DELETE,
    PERMISSIONS.RESTAURANTS.VIEW,
    PERMISSIONS.RESTAURANTS.UPDATE,
    PERMISSIONS.RESTAURANTS.DELETE,
    PERMISSIONS.RESTAURANT_APPLICATIONS.VIEW,
    PERMISSIONS.RESTAURANT_APPLICATIONS.MANAGE,
  ],
  customer: [],
  merchant: [
    PERMISSIONS.DASHBOARD.ACCESS,
    PERMISSIONS.RESTAURANT_APPLICATIONS.CREATE,
  ],
} as const;
