export const CUISINE_NAME_MIN_LENGTH = 3;
export const CUISINE_NAME_MAX_LENGTH = 30;
export const CUISINE_SLUG_MIN_LENGTH = 3;
export const CUISINE_SLUG_MAX_LENGTH = 30;
export const CUISINE_DESCRIPTION_MIN_LENGTH = 10;
export const CUISINE_DESCRIPTION_MAX_LENGTH = 250;

export const CUISINES_HERO_CAROUSEL_LIMIT = 10;
export const CUISINES_LANDING_SECTION_LIMIT = 8;
